apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http        # Must match Service port name
      path: /metrics    # FastAPI exposes metrics here
      interval: 15s
      scrapeTimeout: 10s