apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics         # Must match the Service port name
      path: /               # Prometheus metrics server exposes metrics at root
      interval: 15s
      scrapeTimeout: 10s    # Optional: prevents long scrape hangs